import {test} from 'node:test';import assert from 'node:assert/strict';
import {initialSave,record,mastery,validateSave,checkAnswer,normalizeToken} from '../src/core';
import {exercises} from '../src/content/factory';import {labs} from '../src/content/labs';import {engineering} from '../src/content/engineering';
import type {Attempt,Language,Level} from '../src/types';
const languages:Language[]=['go','rust','java','python','scala'];const levels:Level[]=['beginner','intermediate','advanced'];
test('token checks ignore spacing outside literals but preserve operators and string content',()=>{assert.equal(normalizeToken('x*2'),normalizeToken('x * 2'));assert.notEqual(normalizeToken('"a b"'),normalizeToken('"ab"'));assert.notEqual(normalizeToken('x += 2'),normalizeToken('x + = 2'));});
test('180 unique bilingual exercises; every unit has three forms and seven variants',async()=>{
 const ids=new Set<string>();for(const lang of languages){const {units}=await import(`../src/content/${lang}.ts`);for(const level of levels){const base=exercises(lang,level,units[level]);assert.equal(base.length,12);for(const e of base){assert(!ids.has(e.id));ids.add(e.id);assert(e.title.en&&e.title.es&&e.explanation.en&&e.explanation.es);assert(checkAnswer(e,e.answer));assert(!checkAnswer(e,'definitely wrong answer'));assert(!e.solution.includes('«'));assert(!e.solution.includes('___'));}const alternate=exercises(lang,level,units[level],1);assert.notEqual(base[0].solution,alternate[0].solution);}}
 assert.equal(ids.size,180);
});
test('teaching and worked examples use different variants from the practice prompt',async()=>{for(const language of languages){const {units}=await import(`../src/content/${language}.ts`);for(const level of levels){const sets=[0,1,2,3].map(v=>exercises(language,level,units[level],v));for(let i=0;i<12;i+=3){const practice=sets[0][i];for(const set of sets.slice(1)){assert.notEqual(set[i].solution,practice.solution);assert(set[i].focusLine>=0&&set[i].focusLine<set[i].solution.split('\n').length);}}}}});
const attempt=(overrides:Partial<Attempt>={}):Attempt=>({exercise:'go-beginner-variables-repair',skill:'go-beginner-variables',variant:0,correct:true,hints:0,revealed:false,at:100000000,session:'one',checkpoint:true,mode:'drill',...overrides});
test('review stages advance only on independent sessions, errors review sooner',()=>{let s=initialSave();s=record(s,attempt());assert.equal(s.reviews['go-beginner-variables'].stage,1);assert.equal(s.reviews['go-beginner-variables'].due,100000000+86400000);s=record(s,attempt({at:100000010}));assert.equal(s.reviews['go-beginner-variables'].stage,1);s=record(s,attempt({at:200000000,session:'two',variant:1}));assert.equal(s.reviews['go-beginner-variables'].stage,2);assert.equal(s.reviews['go-beginner-variables'].due,200000000+3*86400000);s=record(s,attempt({correct:false,at:200000010}));assert.equal(s.reviews['go-beginner-variables'].stage,0);assert.equal(s.reviews['go-beginner-variables'].due,200000010+300000);});
test('belts need varied unassisted checkpoints separated by a day',()=>{const a=attempt();assert.equal(mastery([a,attempt({session:'two',variant:1,at:a.at+1000})],'go'),0);assert.equal(mastery([a,attempt({session:'two',variant:1,at:a.at+86400000})],'go'),1);assert.equal(mastery([a,attempt({session:'two',variant:1,at:a.at+86400000,hints:1})],'go'),0);assert.equal(mastery([a,attempt({session:'two',variant:0,at:a.at+86400000})],'go'),0);});
test('backup validation rejects malformed or incompatible progress',()=>{const s=initialSave();assert.deepEqual(validateSave(s),s);for(const v of [null,{}, {...s,version:2},{...s,settings:{...s.settings,volume:99}},{...s,attempts:[{}]},{...s,reviews:{x:{stage:10,due:0,successes:0}}}])assert.throws(()=>validateSave(v));});
test('all twelve labs have two complete scenarios, valid highlights and prediction + application',()=>{assert.equal(labs.length,12);assert.equal(new Set(labs.map(l=>l.id)).size,12);for(const lab of labs){assert.equal(lab.scenarios.length,2);assert(lab.followup.choices.some(c=>c.correct));for(const s of lab.scenarios){assert(s.choices.some(c=>c.correct));assert(s.choices.some(c=>!c.correct));assert(s.question.es);assert(s.frames.length>=4);for(const f of s.frames){assert(f.line>=1&&f.line<=s.code.split('\n').length);assert.equal(f.values.length,s.nodes.length);assert(f.description.en&&f.description.es);assert(f.active.every(i=>i<s.nodes.length));assert(f.edges.every(([a,b])=>a<s.nodes.length&&b<s.nodes.length));}}}});
test('engineering covers six units, twelve cases, and multiple valid tradeoffs',()=>{assert.equal(engineering.length,12);assert.equal(new Set(engineering.map(e=>e.unit.en)).size,6);for(const e of engineering){assert(e.prompt.en&&e.prompt.es);assert(e.choices.some(c=>c.correct));assert(e.choices.some(c=>!c.correct));assert(e.choices.every(c=>c.why.en&&c.why.es));}});
