import {unit} from './factory';
import type {Level,Unit} from '../types';
const p=(body:string,extra='',imports='"fmt"')=>`package main\n\nimport (${imports})\n${extra}\nfunc main() {\n${body}\n}`;
const U=unit;
export const units:Record<Level,Unit[]>={
beginner:[
U('variables','Values that change','Valores que cambian','A short declaration creates a variable; += updates it.','Una declaración corta crea una variable; += la actualiza.','Add the bonus to the current value.','Suma el bono al valor actual.',n=>p(`    score := ${n}\n    score «+=» 2\n    fmt.Println(score)`),n=>`${n+2}`,'='),
U('conditions','Choose a path','Elige un camino','Only the matching branch runs.','Solo se ejecuta la rama que cumple la condición.','The first branch must include the boundary.','La primera rama debe incluir el límite.',n=>p(`    orders := ${n}\n    if orders «>=» ${n} {\n        fmt.Println("ready")\n    } else {\n        fmt.Println("wait")\n    }`),()=> 'ready','>'),
U('loops','One more iteration','Una iteración más','A for loop repeats while its condition is true.','Un bucle for se repite mientras su condición sea verdadera.','Include n in the sum.','Incluye n en la suma.',n=>p(`    total := 0\n    for i := 1; i «<=» ${n}; i++ {\n        total += i\n    }\n    fmt.Println(total)`),n=>`${n*(n+1)/2}`,'<'),
U('functions','Small functions','Funciones pequeñas','Parameters carry inputs; return sends back a result.','Los parámetros reciben entradas; return devuelve un resultado.','Double the parameter, not a constant.','Duplica el parámetro, no una constante.',n=>p(`    fmt.Println(double(${n}))`,`func double(x int) int {\n    return «x * 2»\n}`),n=>`${n*2}`,'x + 2')],
intermediate:[
U('collections','Grow a slice','Amplía un slice','append returns the resulting slice; keep that result.','append devuelve el slice resultante; guarda ese resultado.','append adds one element.','append añade un elemento.',n=>p(`    items := []int{1, 2}\n    items = «append(items, ${n})»\n    fmt.Println(len(items))`),()=> '3','items'),
U('structs','Model an order','Modela un pedido','A struct groups named fields into one value.','Un struct agrupa campos con nombre en un valor.','Read the quantity field.','Lee el campo de cantidad.',n=>p(`    o := Order{Quantity: ${n}}\n    fmt.Println(«o.Quantity» * 2)`,`type Order struct { Quantity int }`),n=>`${n*2}`,'0'),
U('pointers','Update through a pointer','Actualiza mediante un puntero','Dereferencing accesses the value pointed to.','Desreferenciar permite acceder al valor apuntado.','Use * to write through the pointer.','Usa * para escribir mediante el puntero.',n=>p(`    value := ${n}\n    ptr := &value\n    «*ptr» = 10\n    fmt.Println(value)`),()=> '10','valueCopy'),
U('errors','Handle a failure','Gestiona un error','An error result is checked explicitly before using the value.','El resultado error se comprueba antes de usar el valor.','A non-nil error indicates failure.','Un error distinto de nil indica un fallo.',n=>p(`    _, err := strconv.Atoi("order-${n}")\n    if err «!=» nil { fmt.Println("invalid") } else { fmt.Println("valid") }`,'','"fmt"; "strconv"'),()=> 'invalid','==')],
advanced:[
U('interfaces','Behavior as a contract','Comportamiento como contrato','Go interfaces are satisfied implicitly by method sets.','Las interfaces de Go se satisfacen implícitamente mediante métodos.','A Box implements Size.','Box implementa Size.',n=>p(`    var s Sized = Box(${n})\n    fmt.Println(«s.Size()» )`,`type Sized interface { Size() int }\ntype Box int\nfunc (b Box) Size() int { return int(b) }`),n=>`${n}`,'0'),
U('generics','Constrain a type','Restringe un tipo','A type parameter constraint specifies permitted operations.','La restricción de un parámetro de tipo define las operaciones permitidas.','Numbers in this function must support addition.','Los números de esta función deben admitir suma.',n=>p(`    fmt.Println(twice(${n}))`,`func twice[T «int | int64»](x T) T { return x + x }`),n=>`${n*2}`,'any'),
U('goroutines','Wait for work','Espera el trabajo','WaitGroup coordinates completion; Add happens before launching work.','WaitGroup coordina la finalización; Add ocurre antes de lanzar el trabajo.','Wait until Done has been called.','Espera hasta que se llame a Done.',n=>p(`    var wg sync.WaitGroup\n    wg.Add(1)\n    result := 0\n    go func() { defer wg.Done(); result = ${n} * 2 }()\n    «wg.Wait()»\n    fmt.Println(result)`,'','"fmt"; "sync"'),n=>`${n*2}`,'wg.WaitAll()'),
U('channels','Pass a value','Transfiere un valor','Channels communicate values and can synchronize goroutines.','Los canales comunican valores y pueden sincronizar goroutines.','Receive with the left arrow.','Recibe con la flecha hacia la izquierda.',n=>p(`    ch := make(chan int, 1)\n    ch <- ${n}\n    fmt.Println(«<-ch»)`),n=>`${n}`,'ch')]
};
