import {unit as U} from './factory'; import type {Level,Unit} from '../types';
const p=(body:string,extra='')=>`import java.util.*;\nimport java.util.concurrent.*;\npublic class Main {\n${extra}\n    public static void main(String[] args) throws Exception {\n${body}\n    }\n}`;
export const units:Record<Level,Unit[]>={beginner:[
U('types','Declare a value','Declara un valor','An int holds an integer; reassignment changes its value.','Un int contiene un entero; la reasignación cambia su valor.','Add to the existing score.','Suma al puntaje existente.',n=>p(`        int score = ${n};\n        score «+=» 2;\n        System.out.println(score);`),n=>`${n+2}`,'='),
U('conditions','Boundary conditions','Condiciones límite','Choose a boolean comparison that includes the boundary.','Elige una comparación booleana que incluya el límite.','Equal values belong to ready.','Los valores iguales pertenecen a ready.',n=>p(`        int n = ${n};\n        System.out.println(n «>=» ${n} ? "ready" : "wait");`),()=> 'ready','>'),
U('loops','Count every value','Cuenta cada valor','The loop condition is checked before each iteration.','La condición se comprueba antes de cada iteración.','Include the last value.','Incluye el último valor.',n=>p(`        int sum = 0;\n        for (int i = 1; i «<=» ${n}; i++) sum += i;\n        System.out.println(sum);`),n=>`${n*(n+1)/2}`,'<'),
U('methods','A reusable method','Un método reutilizable','A static method can be called without creating an instance.','Un método estático se llama sin crear una instancia.','Return double the input.','Devuelve el doble de la entrada.',n=>p(`        System.out.println(twice(${n}));`,`    static int twice(int x) { return «x * 2»; }`),n=>`${n*2}`,'x + 2')],intermediate:[
U('collections','Grow a list','Amplía una lista','ArrayList is mutable and grows as elements are added.','ArrayList es mutable y crece al añadir elementos.','Add a value without replacing another.','Añade un valor sin reemplazar otro.',n=>p(`        var items = new ArrayList<Integer>(List.of(1, 2));\n        items.«add(${n})»;\n        System.out.println(items.size());`),()=> '3','clear()'),
U('classes','Encapsulate an order','Encapsula un pedido','An instance carries its own fields.','Una instancia contiene sus propios campos.','Read the instance quantity.','Lee la cantidad de la instancia.',n=>p(`        var order = new Order(${n});\n        System.out.println(«order.quantity» * 2);`,`    static class Order { final int quantity; Order(int q) { quantity = q; } }`),n=>`${n*2}`,'0'),
U('interfaces','Program to an interface','Programa con una interfaz','An interface describes behavior supplied by an implementation.','Una interfaz describe comportamiento aportado por una implementación.','Call the interface method.','Llama al método de la interfaz.',n=>p(`        Price p = () -> ${n};\n        System.out.println(«p.amount()»);`,`    interface Price { int amount(); }`),n=>`${n}`,'p'),
U('exceptions','Catch the right failure','Captura el fallo correcto','Parsing invalid numeric text throws NumberFormatException.','Analizar texto numérico inválido lanza NumberFormatException.','Catch the exception produced by parsing.','Captura la excepción del análisis.',n=>p(`        try { Integer.parseInt("order-${n}"); }\n        catch («NumberFormatException» e) { System.out.println("invalid"); }`),()=> 'invalid','NullPointerException')],advanced:[
U('generics','Preserve a type','Conserva un tipo','A generic method relates the input and output types.','Un método genérico relaciona los tipos de entrada y salida.','Return the same type T.','Devuelve el mismo tipo T.',n=>p(`        Integer result = identity(${n});\n        System.out.println(result);`,`    static <T> «T» identity(T value) { return value; }`),n=>`${n}`,'Object'),
U('streams','Map before reducing','Transforma antes de reducir','A terminal operation consumes a stream pipeline.','Una operación terminal consume el flujo.','Double each element.','Duplica cada elemento.',n=>p(`        int sum = List.of(${n}, 2).stream().mapToInt(x -> «x * 2»).sum();\n        System.out.println(sum);`),n=>`${(n+2)*2}`,'x + 2'),
U('equality','Compare values','Compara valores','equals compares String contents; == compares references.','equals compara el contenido de String; == compara referencias.','Use content equality.','Usa igualdad de contenido.',n=>p(`        String a = new String("order-${n}");\n        String b = new String("order-${n}");\n        System.out.println(«a.equals(b)»);`),()=> 'true','a == b'),
U('concurrency','Await a future','Espera un future','join waits for a CompletableFuture result.','join espera el resultado de un CompletableFuture.','Retrieve the completed value.','Recupera el valor completado.',n=>p(`        var future = CompletableFuture.supplyAsync(() -> ${n} * 2);\n        System.out.println(future.«join()»);`),n=>`${n*2}`,'isDone()')]
};
