import {unit as U} from './factory'; import type {Level,Unit} from '../types';
export const units:Record<Level,Unit[]>={beginner:[
U('values','Names and values','Nombres y valores','Assignment binds a name; += updates its bound value.','La asignación vincula un nombre; += actualiza su valor.','Add two to the existing value.','Suma dos al valor existente.',n=>`score = ${n}\nscore «+=» 2\nprint(score)`,n=>`${n+2}`,'='),
U('conditions','Pick a branch','Elige una rama','Indentation groups statements in a branch.','La indentación agrupa instrucciones en una rama.','Include the equality case.','Incluye el caso de igualdad.',n=>`n = ${n}\nif n «>=» ${n}:\n    print("ready")\nelse:\n    print("wait")`,()=> 'ready','>'),
U('loops','Range boundaries','Límites de range','range excludes its stop value.','range excluye su valor final.','Set the stop one beyond n.','Define el límite uno después de n.',n=>`total = 0\nfor i in range(1, «${n+1}»):\n    total += i\nprint(total)`,n=>`${n*(n+1)/2}`,'2'),
U('functions','Return a result','Devuelve un resultado','return sends a value to the caller; print only displays it.','return envía un valor al llamador; print solo lo muestra.','Return double the input.','Devuelve el doble de la entrada.',n=>`def twice(x):\n    return «x * 2»\n\nprint(twice(${n}))`,n=>`${n*2}`,'x + 2')],intermediate:[
U('collections','Mutate a list','Modifica una lista','append mutates the list and returns None.','append modifica la lista y devuelve None.','Append one element.','Añade un elemento.',n=>`items = [1, 2]\nitems.«append(${n})»\nprint(len(items))`,()=> '3','clear()'),
U('classes','Instance state','Estado de una instancia','self refers to the current instance.','self hace referencia a la instancia actual.','Store quantity on self.','Guarda quantity en self.',n=>`class Order:\n    def __init__(self, quantity):\n        «self.quantity» = quantity\n\norder = Order(${n})\nprint(order.quantity * 2)`,n=>`${n*2}`,'quantity'),
U('exceptions','Recover precisely','Recupera con precisión','int raises ValueError for invalid numeric text.','int lanza ValueError para texto numérico inválido.','Catch the conversion error.','Captura el error de conversión.',n=>`try:\n    int("order-${n}")\nexcept «ValueError»:\n    print("invalid")`,()=> 'invalid','KeyError'),
U('modules','Use a module','Usa un módulo','Import a standard-library module before using its functions.','Importa un módulo de la biblioteca estándar antes de usar sus funciones.','math contains isqrt.','math contiene isqrt.',n=>`import «math»\nprint(math.isqrt(${n*n}))`,n=>`${n}`,'random')],advanced:[
U('generators','Yield on demand','Produce bajo demanda','yield pauses a generator; next resumes it.','yield pausa un generador; next lo reanuda.','Yield rather than return a scalar.','Usa yield en lugar de devolver un escalar.',n=>`def values():\n    «yield» ${n}\n    yield ${n+1}\n\ng = values()\nprint(next(g))`,n=>`${n}`,'return'),
U('typing','Describe a generic type','Describe un tipo genérico','Type hints help static tools; Python does not enforce them automatically at runtime.','Las anotaciones ayudan a herramientas estáticas; Python no las impone automáticamente al ejecutar.','Use the same TypeVar in input and output.','Usa el mismo TypeVar en entrada y salida.',n=>`from typing import TypeVar\nT = TypeVar("T")\n\ndef identity(value: T) -> «T»:\n    return value\n\nprint(identity(${n}))`,n=>`${n}`,'MissingType'),
U('async','Await a coroutine','Espera una corrutina','await lets a coroutine wait for another coroutine result.','await permite esperar el resultado de otra corrutina.','Await the coroutine before printing its result.','Espera la corrutina antes de imprimir su resultado.',n=>`import asyncio\n\nasync def work():\n    return ${n} * 2\n\nasync def main():\n    print(«await work()»)\n\nasyncio.run(main())`,n=>`${n*2}`,'work()'),
U('concurrency','Collect worker results','Recoge resultados de workers','Future.result waits for completion. Threads can overlap I/O; CPU parallelism depends on interpreter/build.','Future.result espera la finalización. Los hilos pueden solapar E/S; el paralelismo de CPU depende del intérprete.', 'Read the future result.','Lee el resultado del future.',n=>`from concurrent.futures import ThreadPoolExecutor\n\nwith ThreadPoolExecutor(max_workers=1) as pool:\n    future = pool.submit(lambda: ${n} * 2)\n    print(future.«result()»)`,n=>`${n*2}`,'done()')]
};
