import {unit as U} from './factory'; import type {Level,Unit} from '../types';
const p=(body:string,extra='')=>`${extra}\nfn main() {\n${body}\n}`;
export const units:Record<Level,Unit[]>={beginner:[
U('bindings','Mutable bindings','Bindings mutables','Bindings are immutable unless marked mut.','Los bindings son inmutables salvo que usen mut.','Mark the binding mutable.','Marca el binding como mutable.',n=>p(`    let «mut» score = ${n};\n    score += 2;\n    println!("{}", score);`),n=>`${n+2}`,'const'),
U('conditions','Branch expressions','Expresiones condicionales','if can return a value when both branches have compatible types.','if puede devolver un valor si ambas ramas tienen tipos compatibles.','Include the equality boundary.','Incluye el caso de igualdad.',n=>p(`    let n = ${n};\n    let label = if n «>=» ${n} { "ready" } else { "wait" };\n    println!("{}", label);`),()=> 'ready','>'),
U('loops','Inclusive ranges','Rangos inclusivos','..= includes the end; .. excludes it.','..= incluye el final; .. lo excluye.','Include the last integer.','Incluye el último entero.',n=>p(`    let mut total = 0;\n    for i in «1..=${n}» { total += i; }\n    println!("{}", total);`),n=>`${n*(n+1)/2}`, '1..2'),
U('functions','Return an expression','Devuelve una expresión','The final expression without a semicolon becomes the return value.','La expresión final sin punto y coma es el valor devuelto.','Multiply the input by two.','Multiplica la entrada por dos.',n=>p(`    println!("{}", twice(${n}));`,`fn twice(x: i32) -> i32 { «x * 2» }`),n=>`${n*2}`,'x + 2')],intermediate:[
U('ownership','Move or clone','Mueve o clona','A String move transfers ownership; clone creates another owned value.','Mover un String transfiere su propiedad; clone crea otro valor propio.','Keep a available after creating b.','Mantén a disponible después de crear b.',n=>p(`    let a = String::from("${'x'.repeat(n)}");\n    let b = «a.clone()»;\n    println!("{}", a.len() + b.len());`),n=>`${n*2}`,'a'),
U('borrowing','Borrow to change','Préstamo para modificar','A mutable reference permits changes without moving ownership.','Una referencia mutable permite cambios sin mover la propiedad.','Take a mutable reference.','Toma una referencia mutable.',n=>p(`    let mut n = ${n};\n    let r = «&mut n»;\n    *r += 2;\n    println!("{}", n);`),n=>`${n+2}`,'&n'),
U('collections','Append to a vector','Añade a un vector','Vec stores a growable collection of values of one type.','Vec almacena una colección ampliable de un tipo.', 'push adds one element.','push añade un elemento.',n=>p(`    let mut v = vec![1, 2];\n    «v.push(${n})»;\n    println!("{}", v.len());`),()=> '3','v.clear()'),
U('errors','Recover from Result','Recupera un Result','Result represents success or failure explicitly.','Result representa explícitamente éxito o fallo.','Use the default when parsing fails.','Usa el valor por defecto si falla el análisis.',n=>p(`    let parsed = "bad".parse::<i32>();\n    println!("{}", parsed.«unwrap_or(${n})»);`),n=>`${n}`,'unwrap()')],advanced:[
U('traits','Generic behavior','Comportamiento genérico','Trait bounds make required behavior explicit.','Los límites de traits hacen explícito el comportamiento requerido.','Display permits formatting with {}.','Display permite formatear con {}.',n=>p(`    show(${n});`,`fn show<T: «std::fmt::Display»>(value: T) { println!("{}", value); }`),n=>`${n}`,'Sized'),
U('lifetimes','Relate lifetimes','Relaciona lifetimes','A lifetime annotation relates borrows; it does not extend their duration.','Una anotación relaciona préstamos; no extiende su duración.','Return a borrow tied to the input.','Devuelve un préstamo ligado a la entrada.',n=>p(`    let a = String::from("${'x'.repeat(n)}");\n    println!("{}", first(&a).len());`,`fn first<'a>(x: &'a str) -> «&'a str» { x }`),n=>`${n}`,"&'static str"),
U('iterators','Transform lazily','Transforma de forma perezosa','map is lazy; sum consumes the iterator.','map es perezoso; sum consume el iterador.','Double each value before summing.','Duplica cada valor antes de sumar.',n=>p(`    let values = vec![${n}, 2];\n    let total: i32 = values.iter().map(|x| «x * 2»).sum();\n    println!("{}", total);`),n=>`${(n+2)*2}`,'x + 2'),
U('concurrency','Join a thread','Espera un hilo','join waits for a thread and returns its result.','join espera un hilo y devuelve su resultado.','Join before unwrapping the thread result.','Espera el hilo antes de extraer el resultado.',n=>p(`    let handle = std::thread::spawn(|| ${n} * 2);\n    println!("{}", handle.«join()».unwrap());`),n=>`${n*2}`,'result()')]
};
