import {unit as U} from './factory'; import type {Level,Unit} from '../types';
const p=(body:string,extra='')=>`${extra}\n@main def run(): Unit = {\n${body}\n}`;
export const units:Record<Level,Unit[]>={beginner:[
U('values','val or var','val o var','val cannot be reassigned; var can.','val no se puede reasignar; var sí.', 'Choose a mutable binding.','Elige un binding mutable.',n=>p(`  «var» score = ${n}\n  score += 2\n  println(score)`),n=>`${n+2}`,'val'),
U('conditions','if is an expression','if es una expresión','Both branches produce the value of an if expression.','Las ramas producen el valor de la expresión if.','Include equal values.','Incluye los valores iguales.',n=>p(`  val n = ${n}\n  println(if n «>=» ${n} then "ready" else "wait")`),()=> 'ready','>'),
U('collections','Transform a list','Transforma una lista','map produces a new collection from each element.','map produce una colección nueva a partir de cada elemento.','Double each value.','Duplica cada valor.',n=>p(`  val values = List(${n}, 2)\n  println(values.map(x => «x * 2»).sum)`),n=>`${(n+2)*2}`,'x + 2'),
U('functions','A concise function','Una función concisa','The body expression supplies the return value.','La expresión del cuerpo proporciona el valor devuelto.','Multiply the input.','Multiplica la entrada.',n=>p(`  println(twice(${n}))`,`def twice(x: Int): Int = «x * 2»`),n=>`${n*2}`,'x + 2')],intermediate:[
U('case-classes','Copy immutable data','Copia datos inmutables','copy creates a new case-class instance with selected fields changed.','copy crea una instancia nueva con campos seleccionados modificados.','Create a copy with a new quantity.','Crea una copia con una cantidad nueva.',n=>p(`  val order = Order(${n})\n  val updated = order.«copy(quantity = ${n+2})»\n  println(updated.quantity)`,`case class Order(quantity: Int)`),n=>`${n+2}`,'copy()'),
U('patterns','Match a shape','Reconoce una forma','Pattern matching chooses a case based on structure.','El pattern matching elige un caso según la estructura.','Extract the value from Some.','Extrae el valor de Some.',n=>p(`  val value: Option[Int] = Some(${n})\n  val result = value match {\n    case «Some(x)» => x * 2\n    case None => 0\n  }\n  println(result)`),n=>`${n*2}`,'None'),
U('options','Handle absence','Gestiona la ausencia','Option represents a present or absent value.','Option representa un valor presente o ausente.','Provide a default for None.','Proporciona un valor por defecto para None.',n=>p(`  val value: Option[Int] = None\n  println(value.«getOrElse(${n})»)`),n=>`${n}`,'get'),
U('traits','Define behavior','Define comportamiento','A trait defines a contract that implementations fulfill.','Un trait define un contrato que cumplen las implementaciones.','Call amount on the implementation.','Llama a amount en la implementación.',n=>p(`  val p: Price = new Price { def amount: Int = ${n} }\n  println(«p.amount» )`,`trait Price { def amount: Int }`),n=>`${n}`,'p')],advanced:[
U('variance','A covariant box','Una caja covariante','+A permits Box[String] where Box[Any] is expected for this immutable producer.','+A permite Box[String] donde se espera Box[Any] para este productor inmutable.','Mark the type parameter covariant.','Marca el parámetro como covariante.',n=>p(`  val small: Box[String] = Box("${n}")\n  val wide: Box[Any] = small\n  println(wide.value)`,`case class Box[«+A»](value: A)`),n=>`${n}`,'A'),
U('composition','Compose operations','Compón operaciones','andThen applies the left function followed by the right.','andThen aplica la función izquierda seguida de la derecha.','Add one, then double.','Suma uno y luego duplica.',n=>p(`  val addOne: Int => Int = _ + 1\n  val double: Int => Int = _ * 2\n  val combined = addOne.«andThen»(double)\n  println(combined(${n}))`),n=>`${(n+1)*2}`,'compose'),
U('futures','Await a demonstration','Espera una demostración','Await blocks here for a tiny console demo; production async flows usually compose futures.','Await bloquea en esta demostración; los flujos asíncronos de producción suelen componer futures.','Obtain the completed result.','Obtén el resultado completado.',n=>p(`  val f = Future(${n} * 2)\n  println(Await.«result»(f, 2.seconds))`,`import scala.concurrent.{Future, Await}\nimport scala.concurrent.ExecutionContext.Implicits.global\nimport scala.concurrent.duration.*`),n=>`${n*2}`,'ready'),
U('context','Contextual parameters','Parámetros contextuales','using requests a contextual argument supplied by a matching given.','using solicita un argumento contextual aportado por un given compatible.','Mark the parameter contextual.','Marca el parámetro como contextual.',n=>p(`  given Int = 2\n  println(scale(${n}))`,`def scale(x: Int)(«using» factor: Int): Int = x * factor`),n=>`${n*2}`,'implicitWrong')]
};
