import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
const executablePath=process.env.CHROME_PATH;
const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});
await mkdir('test-results',{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:1100},locale:'en-US'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');await page.getByRole('heading',{name:'Values that change',exact:true}).waitFor();
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
assert.equal(await page.getByLabel('Your predicted output').count(),0);
await page.getByRole('button',{name:'Show me how it works',exact:true}).click();
await page.getByRole('button',{name:'Next explanation step',exact:true}).click();
await page.getByRole('button',{name:'Next explanation step',exact:true}).click();
await page.getByRole('button',{name:'Next explanation step',exact:true}).click();
await page.screenshot({path:'test-results/lesson-animation.png',fullPage:true});
await page.getByRole('button',{name:'Show me two examples',exact:true}).click();
await page.getByRole('button',{name:'See the second example',exact:true}).click();
await page.getByRole('button',{name:'I’m ready — let me try',exact:true}).click();
await page.getByLabel('Your predicted output').fill('5');await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByText('Well done. Now make the idea yours.').waitFor();
await page.getByRole('button',{name:'Next challenge',exact:true}).click();await page.getByLabel('Your replacement expression').fill('+=');await page.getByRole('button',{name:'Check answer',exact:true}).click();await page.getByText('Well done. Now make the idea yours.').waitFor();
await page.getByRole('button',{name:'Visual lab',exact:true}).click();await page.getByRole('heading',{name:'Inside the call stack',exact:true}).waitFor();
await page.getByRole('button',{name:'Next step',exact:true}).click();await page.getByRole('button',{name:'Next step',exact:true}).click();await page.getByRole('heading',{name:'What reaches the caller?'}).waitFor();
assert(await page.getByRole('button',{name:'Next step',exact:true}).isDisabled());await page.getByRole('button',{name:'A 6',exact:true}).click();await page.getByRole('button',{name:'Reveal the outcome',exact:true}).click();await page.getByRole('heading',{name:'Repair descend for nonnegative inputs.'}).waitFor();
await page.screenshot({path:'test-results/lab-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Engineering',exact:true}).click();await page.getByRole('heading',{name:'Name the decision',exact:true}).waitFor();await page.getByRole('button',{name:'A qualifies_for_free_shipping(order)',exact:true}).click();await page.getByText('The name describes the business decision and keeps the condition together.').waitFor();
await page.getByLabel('Interface language / Idioma').selectOption('es');await page.getByRole('heading',{name:'Nombra la decisión',exact:true}).waitFor();
await page.getByRole('button',{name:'Dojo diario',exact:true}).click();await page.getByRole('button',{name:'Python',exact:true}).click();await page.locator('#level').selectOption('advanced');await page.getByRole('heading',{name:'Produce bajo demanda',exact:true}).waitFor();
await page.reload();await page.getByRole('heading',{name:'Produce bajo demanda',exact:true}).waitFor();assert.equal(await page.locator('#level').inputValue(),'advanced');
await page.getByRole('button',{name:'Configuración y progreso'}).click();await page.getByRole('button',{name:'Cerrar',exact:true}).click();
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true,locale:'es-MX'});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://127.0.0.1:5173');await mobile.getByRole('heading',{name:'Valores que cambian',exact:true}).waitFor();
assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:'test-results/iphone.png',fullPage:true});
await mobile.getByRole('button',{name:'Código',exact:true}).click();await mobile.getByRole('textbox',{name:'Editor de código'}).waitFor();await mobile.getByRole('button',{name:'Lección',exact:true}).click();
await mobile.getByRole('button',{name:'Laboratorio visual',exact:true}).click();await mobile.getByRole('heading',{name:'Dentro de la pila',exact:true}).waitFor();await mobile.screenshot({path:'test-results/iphone-lab.png',fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await mobile.emulateMedia({reducedMotion:'reduce'});assert.equal(await mobile.locator('.flow-edge').first().evaluate(el=>getComputedStyle(el).animationName),'none');
assert.deepEqual(errors,[]);await browser.close();console.log('PASS desktop + mobile: drills, prediction gates, engineering, locale, persistence, tabs, reduced motion, no runtime errors.');
