import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronRight,Code2,Flame,GitBranch,GraduationCap,Headphones,Lightbulb,PanelLeft,Play,RotateCcw,Settings,Terminal,Volume2,VolumeX,X,Download,Upload,BookOpen,Clock,Layers,Activity} from 'lucide-react';
import Editor from './Editor';
import GuidedLesson,{LessonPath,type Phase} from './GuidedLesson';
import {bi,type Attempt,type Exercise,type Language,type Level,type Save} from './types';
import {initialSave,loadSave,persist,record,mastery,checkAnswer,skillOf,validateSave,cue} from './core';
import {exercises} from './content/factory';
const LabView=lazy(()=>import('./LabView'));
const EngineeringView=lazy(()=>import('./EngineeringView'));
const names:Record<Language,string>={go:'Go',rust:'Rust',java:'Java',python:'Python',scala:'Scala'};
const loaders={go:()=>import('./content/go'),rust:()=>import('./content/rust'),java:()=>import('./content/java'),python:()=>import('./content/python'),scala:()=>import('./content/scala')};
const labNames=[['stack','Inside the call stack','Dentro de la pila'],['references','Two names, one object','Dos nombres, un objeto'],['ownership','Who owns this value?','¿Quién posee este valor?'],['gc','What can be collected?','¿Qué se puede recolectar?'],['races','The lost update','La actualización perdida'],['deadlock','Waiting forever','Esperando para siempre'],['async','Waiting without blocking','Esperar sin bloquear'],['generics','One shape, many types','Una forma, muchos tipos'],['lazy','Work only when asked','Trabaja solo cuando se pide'],['layers','Follow an order','Sigue un pedido'],['queues','When a message returns','Cuando vuelve un mensaje'],['git','Two branches meet','Dos ramas se encuentran']];
const engineeringNames=[['name','Name the decision','Nombra la decisión'],['extract','Split a tangled function','Divide una función enredada'],['modules','Draw the boundary','Dibuja el límite'],['cycle','Break a dependency cycle','Rompe un ciclo de dependencias'],['tests','Test the boundary','Prueba el límite'],['regression','Refactor with a safety net','Refactoriza con protección'],['commits','Make a reviewable commit','Crea un commit revisable'],['review','Review the behavior','Revisa el comportamiento'],['injection','Replace a dependency in tests','Reemplaza una dependencia en pruebas'],['architecture','Choose architecture','Elige arquitectura'],['idempotency','Retry without double charging','Reintenta sin cobrar dos veces'],['cache','Bound stale inventory','Limita inventario obsoleto']];
export default function App(){
 const [save,setSave]=useState<Save>(initialSave),[loaded,setLoaded]=useState(false),[storageError,setStorageError]=useState('');
 const [lessonCode,setLessonCode]=useState(''),[phase,setPhase]=useState<Phase>('lesson'),[teaching,setTeaching]=useState<Exercise[][]>([]);
 const [mode,setMode]=useState<'daily'|'labs'|'engineering'>('daily'),[all,setAll]=useState<Exercise[]>([]),[index,setIndex]=useState(0),[variant,setVariant]=useState(0),[code,setCode]=useState(''),[answer,setAnswer]=useState(''),[hints,setHints]=useState(0),[revealed,setRevealed]=useState(false),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[checked,setChecked]=useState(false);
 const [lab,setLab]=useState('stack'),[eng,setEng]=useState('name'),[settings,setSettings]=useState(false),[catalog,setCatalog]=useState(false),[insert,setInsert]=useState<{text:string;key:number}>(),[stdin,setStdin]=useState('');
 const [caps,setCaps]=useState<Record<string,{available:boolean;version:string}>|null>(null),[running,setRunning]=useState(false),[output,setOutput]=useState(''),[free,setFree]=useState(false),[session,setSession]=useState(()=>crypto.randomUUID()),[remaining,setRemaining]=useState(300),[timerActive,setTimerActive]=useState(false);
 const active=useRef(''),request=useRef(0),file=useRef<HTMLInputElement>(null),dirty=useRef(false);
 const {locale,language,level,sound,volume,timed}=save.settings;const t=(en:string,es:string)=>locale==='es'?es:en;
 const e=all[index];active.current=e?`${e.id}:${e.variant}:${mode}`:'';
 useEffect(()=>{loadSave().then(s=>{const requested=new URLSearchParams(location.search).get('lang');setSave(requested==='es'||requested==='en'?{...s,settings:{...s.settings,locale:requested}}:s);setVariant(s.attempts.length%7);}).catch(()=>setStorageError('storage')).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(loaded)persist(save).catch(()=>setStorageError('storage'));},[save,loaded]);
 useEffect(()=>{document.documentElement.lang=locale;},[locale]);
 useEffect(()=>{let cancelled=false;loaders[language]().then(m=>{if(!cancelled){setAll(exercises(language,level,m.units[level],variant));setTeaching([1,2,3].map(offset=>exercises(language,level,m.units[level],variant+offset)));setIndex(0);}});return()=>{cancelled=true;};},[language,level,variant]);
 useEffect(()=>{if(!e)return;setCode(e.code);setAnswer('');setHints(0);setRevealed(false);setFeedback(null);setChecked(false);setOutput('');setFree(false);dirty.current=false;},[e?.id,e?.variant]);
 useEffect(()=>{if(import.meta.env.DEV&&['localhost','127.0.0.1'].includes(location.hostname))fetch('/api/capabilities').then(r=>r.ok?r.json():null).then(setCaps).catch(()=>setCaps(null));},[]);
 useEffect(()=>{if(!timed||!timerActive||remaining<=0)return;const timer=setInterval(()=>setRemaining(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer);},[timed,timerActive,remaining]);
 useEffect(()=>{setPhase('lesson');},[e?.unit,e?.language,e?.level]);
 const advanceLesson=()=>{if(phase==='lesson')setPhase('animation');else if(phase==='animation')setPhase('examples');else {setPhase('practice');setCode(e?.code??'');setOutput('');}};
 const changePhase=(p:Phase)=>{if(p==='practice')setCode(e?.code??'');setPhase(p);};
 useEffect(()=>{if(!settings&&!catalog)return;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');const previous=document.activeElement as HTMLElement;const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]')??[]);focusable()[0]?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setSettings(false);setCatalog(false);}if(event.key==='Tab'){const list=focusable(),first=list[0],last=list[list.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[settings,catalog]);
 const changeSettings=(patch:Partial<Save['settings']>)=>setSave(s=>({...s,settings:{...s.settings,...patch}}));
 const attempt=(a:Omit<Attempt,'at'|'session'>)=>{setSave(s=>record(s,{...a,at:Date.now(),session}));cue(sound,volume,a.correct?'success':'retry');};
 const check=()=>{if(!e||checked||phase!=='practice')return;const ok=checkAnswer(e,answer);attempt({exercise:e.id,skill:skillOf(e),variant:e.variant,correct:ok,hints,revealed,checkpoint:e.checkpoint,mode:'drill'});setFeedback({ok,text:ok?t('Well done. Now make the idea yours.','Bien hecho. Ahora haz tuya la idea.'):t('Not quite. Trace the values and try a hint.','Todavía no. Sigue los valores y prueba una pista.')});setChecked(true);};
 const next=()=>{const due=all.findIndex((x,i)=>i!==index&&(save.reviews[skillOf(x)]?.due??Infinity)<=Date.now());if(due>=0)setIndex(due);else if(index<all.length-1)setIndex(index+1);else setVariant(v=>v+1);};
 const reveal=()=>{setRevealed(true);setHints(3);attempt({exercise:e.id,skill:skillOf(e),variant:e.variant,correct:false,hints:3,revealed:true,checkpoint:e.checkpoint,mode:'drill'});};
 const run=async()=>{if(!e||running)return;const current=active.current,req=++request.current;setRunning(true);setOutput(t('Compiling and running…','Compilando y ejecutando…'));try{const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({language,source:mode==='daily'&&phase!=='practice'?lessonCode:code,stdin,...(free?{}:{expected:mode==='daily'&&phase==='practice'?e.expected:undefined})})});const result=await response.json();if(active.current!==current||req!==request.current)return;if(!response.ok)throw new Error(result.error);setOutput([result.status==='ok'?t('Execution complete','Ejecución completa'):result.status,result.diagnostics,result.stdout,result.stderr,...(result.tests??[]).map((x:{passed:boolean;expected?:string;actual:string})=>x.expected===undefined?'':`${x.passed?'✓':'✕'} ${t('Expected','Esperado')}: ${x.expected} · ${t('Actual','Actual')}: ${x.actual}`)].filter(Boolean).join('\n'));if(!free&&mode==='daily'&&phase==='practice'){const ok=result.status==='ok'&&result.tests?.every((x:{passed:boolean})=>x.passed);attempt({exercise:e.id,skill:skillOf(e),variant:e.variant,correct:!!ok,hints:Math.max(hints,e.kind==='predict'?1:0),revealed,checkpoint:false,mode:'run'});}}catch(err){if(active.current===current)setOutput(t('Runner error: ','Error del runner: ')+(err as Error).message);}finally{setRunning(false);}};
 const completed=new Set(save.attempts.filter(a=>a.correct).map(a=>a.exercise)).size;
 const dailyAttempts=save.attempts.filter(a=>a.mode==='drill'&&a.skill.startsWith(`${language}-${level}`));
 const independent=dailyAttempts.filter(a=>!a.hints&&!a.revealed),accuracy=independent.length?Math.round(independent.filter(a=>a.correct).length/independent.length*100):0;
 const mastered=mastery(save.attempts,`${language}-${level}`),due=Object.values(save.reviews).filter(r=>r.due<=Date.now()).length;
 const count=save.attempts.filter(a=>a.session===session&&a.correct).length;
 const startSession=()=>{setPhase('lesson');setSession(crypto.randomUUID());setVariant(v=>v+1);setRemaining(300);setTimerActive(timed);};
 const exportSave=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(save,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`code-dojo-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const importSave=async(f?:File)=>{if(!f)return;try{if(f.size>10000000)throw Error();const value=validateSave(JSON.parse(await f.text()));setSave(value);setStorageError('');}catch{setStorageError('import');}if(file.current)file.current.value='';};
 const entries=mode==='daily'?all.map((x,i)=>({id:String(i),title:x.title[locale],kind:x.kind})): (mode==='labs'?labNames:engineeringNames).map(x=>({id:x[0],title:x[locale==='en'?1:2],kind:''}));
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="#" onClick={ev=>{ev.preventDefault();setMode('daily');}}><span className="brand-mark">井</span><span>code<span className="brand-light">dojo</span><small>{t('BUILD YOUR INSTINCT','DESARROLLA TU INSTINTO')}</small></span></a><nav className="main-nav" aria-label={t('Practice modes','Modos de práctica')}>{([['daily',Code2,t('Daily dojo','Dojo diario')],['labs',Activity,t('Visual lab','Laboratorio visual')],['engineering',GitBranch,t('Engineering','Ingeniería')]] as const).map(([key,Icon,label])=><button key={key} className={mode===key?'nav-active':''} onClick={()=>{setMode(key);}}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="top-actions"><select className="locale-select" aria-label="Interface language / Idioma" value={locale} onChange={ev=>changeSettings({locale:ev.target.value as 'en'|'es'})}><option value="en">English</option><option value="es">Español</option></select><button className="icon-button" aria-label={t('Settings and progress','Configuración y progreso')} onClick={()=>setSettings(true)}><Settings size={19}/></button><span className="avatar">{t('You','Tú')}</span></div></header>
  <main><div className="page-intro"><div><div className="eyebrow"><span className="live-dot"/>{t('A LITTLE PRACTICE. EVERY DAY.','UN POCO DE PRÁCTICA. CADA DÍA.')}</div><h1>{mode==='daily'?<>{t('Small reps.','Repeticiones pequeñas.')} <em>{t('Strong instincts.','Instintos fuertes.')}</em></>:mode==='labs'?<>{t('See the code.','Observa el código.')} <em>{t('Understand the why.','Entiende el porqué.')}</em></>:<>{t('Beyond syntax.','Más allá de la sintaxis.')} <em>{t('Think like an engineer.','Piensa como ingeniero.')}</em></>}</h1><p>{t('Read it. Break it. Write it. Make it second nature.','Léelo. Rómpelo. Escríbelo. Hazlo parte de ti.')}</p></div><button className="session-button" onClick={startSession}><Flame size={19}/><span><b>{count} {t('reps this session','repeticiones')}</b><small>{t('Start a fresh session','Iniciar otra sesión')} <ArrowUpRight size={12}/></small></span></button></div>
  <div className="workspace-toolbar"><div className="language-list">{(Object.keys(names) as Language[]).map(l=><button key={l} aria-pressed={language===l} className={language===l?'selected':''} onClick={()=>changeSettings({language:l})}><span className={`language-dot ${l}`}/>{names[l]}{language===l&&<Check size={13}/>}</button>)}</div><div className="toolbar-right"><label className="sr-only" htmlFor="level">{t('Level','Nivel')}</label><select id="level" value={level} onChange={ev=>changeSettings({level:ev.target.value as Level})}><option value="beginner">{t('Beginner','Principiante')}</option><option value="intermediate">{t('Intermediate','Intermedio')}</option><option value="advanced">{t('Advanced','Avanzado')}</option></select><button className="catalog-button" onClick={()=>setCatalog(true)}><BookOpen size={16}/>{t('Curriculum','Temario')}</button></div></div>

  <div className="workspace single-workspace">
   <section className="lesson-panel" aria-label={t('Instructions','Instrucciones')}>
    <div className="panel-bar"><span><span className="live-dot"/>{mode==='daily'?(phase==='practice'?t('YOUR NEXT CHALLENGE','TU SIGUIENTE RETO'):t('LEARN BEFORE YOU PRACTICE','APRENDE ANTES DE PRACTICAR')):mode==='labs'?t('EXPLORE A CONCEPT','EXPLORA UN CONCEPTO'):t('THINK IN SYSTEMS','PIENSA EN SISTEMAS')}</span><span>{mode==='daily'?`${index+1} / 12`:mode==='labs'?'12 LABS':'12 KATAS'}</span></div>
    {mode==='daily'&&e&&<LessonPath phase={phase} locale={locale} onChange={changePhase}/>}
    {mode==='daily'&&e&&phase!=='practice'&&teaching.length===3&&<GuidedLesson phase={phase} lesson={teaching[0][Math.floor(index/3)*3+1]} examples={[teaching[1][Math.floor(index/3)*3+1],teaching[2][Math.floor(index/3)*3+1]]} locale={locale} onNext={advanceLesson} onCode={setLessonCode} onStep={()=>cue(sound,volume,'step')}/>}
    {mode==='daily'&&e&&phase==='practice'&&<div className="lesson-content"><div className="breadcrumb">{names[language]}<ChevronRight size={12}/>{t(level,level==='beginner'?'Principiante':level==='intermediate'?'Intermedio':'Avanzado')}<ChevronRight size={12}/>{t('Unit','Unidad')} {Math.floor(index/3)+1}</div><div className="lesson-badges"><span className="pill">{e.kind==='predict'?t('01 · READ & PREDICT','01 · LEE Y PREDICE'):e.kind==='complete'?t('02 · FILL THE GAP','02 · COMPLETA'):t('03 · FIX THE BUG','03 · REPARA')}</span><span className="muted"><Clock size={13}/>{e.kind==='predict'?'~30s':'~60s'}</span></div><h2>{e.title[locale]}</h2><p className="lede">{e.kind==='predict'?t('Read the code below. What will it print? Trace each step before you answer.','Lee el código. ¿Qué imprimirá? Sigue cada paso antes de responder.'):e.kind==='complete'?t('Complete the missing expression. Write only what belongs in the gap.','Completa la expresión que falta. Escribe solo lo que va en el espacio.'):t('One expression is wrong. Find the bug and write the corrected expression.','Una expresión es incorrecta. Encuentra el error y escribe la expresión corregida.')}</p>
     <div className="concept-card"><div className="concept-icon"><Layers size={19}/></div><div><span>{t('THE IDEA','LA IDEA')}</span><p>{e.explanation[locale]}</p></div></div>
   <section className="code-panel" aria-label={t('Editor and output','Editor y salida')}><div className="panel-bar"><span className="file-label"><span className={`language-dot ${language}`}/>{({go:'main.go',rust:'main.rs',java:'Main.java',python:'main.py',scala:'Main.scala'})[language]}</span><div className="editor-actions"><span>{caps?.[language]?.available?t('LOCAL RUNNER','RUNNER LOCAL'):t('PRACTICE MODE','MODO PRÁCTICA')}</span><button className="icon-button" aria-label={t('Reset code','Restablecer código')} onClick={()=>{setCode(e?.code??'');setOutput('');}}><RotateCcw size={15}/></button></div></div>
    {mode!=='daily'&&<div className="scratch-note">{t('Independent scratchpad · editing this code does not change the conceptual diagram.','Bloc independiente · editar este código no cambia el diagrama conceptual.')}</div>}
    <Editor value={mode==='daily'&&phase!=='practice'?lessonCode:code} language={language} label={t('Code editor','Editor de código')} onChange={v=>{if(mode==='daily'&&phase!=='practice')setLessonCode(v);else setCode(v);dirty.current=true;}} insert={insert}/>
    <div className="symbol-bar" aria-label={t('Code symbols','Símbolos de código')}>{['{','}','(',')','[',']',';',':','=','<','>','"','    '].map(x=><button key={x} aria-label={x==='    '?t('Indent','Indentar'):x} onClick={()=>setInsert({text:x,key:Date.now()})}>{x==='    '?'⇥':x}</button>)}</div>
    <div className="editor-footer"><span>UTF-8 <span>•</span> {names[language]}</span><button className="run-button" disabled={!caps?.[language]?.available||running} onClick={run}><Play size={14}/>{running?t('Running…','Ejecutando…'):t('Run code','Ejecutar código')}</button></div>
    <div className="terminal-panel"><div className="terminal-heading"><span><Terminal size={15}/>{t('OUTPUT','SALIDA')}</span><span className="terminal-dots"><i/><i/><i/></span></div>{output?<pre role="status">{output}</pre>:<div className="terminal-empty"><span className="prompt-symbol">❯</span><p>{caps?.[language]?.available?t('Ready when you are. Run your code to see what happens.','Cuando quieras. Ejecuta tu código para ver qué ocurre.'):(phase==='practice'?t('Predict first. Browser mode checks exercise answers without executing code.','Primero predice. El modo navegador comprueba respuestas sin ejecutar código.'):t('Start with the lesson. The worked examples show expected output; local execution is optional.','Comienza con la lección. Los ejemplos resueltos muestran la salida esperada; ejecutar localmente es opcional.'))}</p><span className="cursor"/></div>}
    {caps?.[language]?.available&&<div className="run-options"><label><input type="checkbox" checked={free} onChange={ev=>setFree(ev.target.checked)}/>{t('Free scratchpad (no exercise test)','Bloc libre (sin prueba del ejercicio)')}</label><label>{t('Standard input','Entrada estándar')}<textarea value={stdin} onChange={ev=>setStdin(ev.target.value)} rows={2}/></label></div>}
    {caps&&!caps[language]?.available&&<p className="runner-note">{t('Install the toolchain and restart the app to enable local execution.','Instala las herramientas del lenguaje y reinicia la app para habilitar ejecución local.')}</p>}</div>
   </section>
     <form onSubmit={ev=>{ev.preventDefault();check();}}><label className="answer-label" htmlFor="answer">{e.kind==='predict'?t('Your predicted output','Tu salida predicha'):t('Your replacement expression','Tu expresión de reemplazo')}</label><div className="answer-wrap"><Terminal size={17}/><input id="answer" value={answer} autoComplete="off" autoCapitalize="off" spellCheck={false} placeholder={t('Type your answer…','Escribe tu respuesta…')} onChange={ev=>{setAnswer(ev.target.value);if(checked&&!feedback?.ok)setHints(h=>Math.max(1,h));setChecked(false);setFeedback(null);}}/><kbd>↵</kbd></div><div className="answer-actions"><button className="primary" disabled={!answer.trim()||checked} type="submit">{t('Check answer','Comprobar')}<ArrowRight size={17}/></button><button type="button" className="hint-button" onClick={()=>setHints(h=>Math.min(2,h+1))} disabled={hints>=2}><Lightbulb size={16}/>{t('A little hint','Una pista')} <span>{Math.min(hints,2)}/2</span></button></div></form>
     {hints>0&&<div className="hint-box">{e.hints[Math.min(hints,2)-1][locale]}{hints>=2&&!revealed&&<button onClick={reveal}>{t('Reveal solution and review later','Revelar solución y repasar después')}</button>}</div>}
     {revealed&&<pre className="solution">{e.solution}</pre>}
     {feedback&&<div className={`feedback ${feedback.ok?'success':'retry'}`} role="status">{feedback.ok?<Check size={19}/>:<RotateCcw size={18}/>}<span>{feedback.text}</span></div>}
     <div className="lesson-bottom"><span>{t('Exercise check · not compiler execution','Comprobación del ejercicio · no compilación')}</span><button onClick={next}>{feedback?.ok?t('Next challenge','Siguiente reto'):t('Skip for now','Saltar por ahora')}<ArrowRight size={15}/></button></div>
    </div>}
    <Suspense fallback={<div className="lesson-content">{t('Loading lesson…','Cargando lección…')}</div>}>{mode==='labs'&&<LabView id={lab} locale={locale} onStep={()=>cue(sound,volume,'step')} onAttempt={(correct,v,checkpoint)=>attempt({exercise:`lab-${lab}-${v}-${checkpoint?'prediction':'application'}`,skill:`lab-${lab}`,variant:v,correct,hints:0,revealed:false,checkpoint,mode:'lab'})}/>} {mode==='engineering'&&<EngineeringView id={eng} locale={locale} onAttempt={correct=>attempt({exercise:`eng-${eng}`,skill:`eng-${eng}`,variant:0,correct,hints:0,revealed:false,checkpoint:true,mode:'engineering'})}/>}</Suspense>
   </section>


  </div>
  <div className="progress-strip"><div className="belt-icon"><GraduationCap size={24}/></div><div className="belt-info"><b>{mastered>=4?t('Green belt','Cinturón verde'):mastered>=2?t('Yellow belt','Cinturón amarillo'):t('White belt','Cinturón blanco')}</b><span>{mastered}/4 {t('skills retained across sessions','habilidades retenidas entre sesiones')}</span></div><div className="belt-track"><span style={{width:`${mastered/4*100}%`}}/></div><div className="stat"><b>{accuracy}%</b><span>{t('Unassisted accuracy','Precisión sin ayuda')}</span></div><div className="stat"><b>{due}</b><span>{t('Skills due for review','Habilidades para repasar')}</span></div><button className="icon-button sound-toggle" aria-label={sound?t('Mute sound','Silenciar'):t('Enable sound','Activar sonido')} onClick={()=>{changeSettings({sound:!sound});cue(!sound,volume,'step');}}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></div>
  <footer className="page-footer"><span><span className="live-dot"/>{t('Progress stays on this device','El progreso queda en este dispositivo')}</span><span>{t('Consistency over speed. Curiosity over perfection.','Constancia antes que velocidad. Curiosidad antes que perfección.')}</span><span>{timed?<button onClick={()=>setTimerActive(!timerActive)}><Clock size={13}/>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} {remaining===0?t('Round complete','Ronda completa'):timerActive?t('Pause','Pausar'):t('Start','Iniciar')}</button>:t('No timer. No pressure.','Sin reloj. Sin presión.')}</span></footer>
  {storageError&&<div className="storage-warning" role="alert">{storageError==='import'?t('Could not import: choose a valid Code Dojo backup.','No se pudo importar: elige un respaldo válido de Code Dojo.'):t('Device storage is unavailable. Export a backup before leaving.','El almacenamiento no está disponible. Exporta un respaldo antes de salir.')}</div>}
  </main>
  {catalog&&<div className="modal-backdrop" onClick={()=>setCatalog(false)}><section className="modal catalog" role="dialog" aria-modal="true" aria-label={t('Curriculum','Temario')} onClick={ev=>ev.stopPropagation()}><div className="modal-heading"><h2>{t('Choose your next rep','Elige tu siguiente reto')}</h2><button className="icon-button" onClick={()=>setCatalog(false)} aria-label={t('Close','Cerrar')}><X/></button></div><div className="catalog-list">{entries.map((x,i)=><button key={x.id} onClick={()=>{if(mode==='daily')setIndex(Number(x.id));else if(mode==='labs')setLab(x.id);else setEng(x.id);setCatalog(false);}}><span className="catalog-number">{String(i+1).padStart(2,'0')}</span><span>{x.title}<small>{mode==='daily'?({predict:t('Predict','Predice'),complete:t('Complete','Completa'),repair:t('Repair','Repara')}[x.kind]??''):mode==='labs'?t('2 scenarios · prediction + application','2 escenarios · predicción + aplicación'):t('Order-processing case study','Caso de procesamiento de pedidos')}</small></span><ChevronRight size={17}/></button>)}</div></section></div>}
  {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-label={t('Settings','Configuración')} onClick={ev=>ev.stopPropagation()}><div className="modal-heading"><h2>{t('Your dojo','Tu dojo')}</h2><button className="icon-button" onClick={()=>setSettings(false)} aria-label={t('Close','Cerrar')}><X/></button></div><p className="muted">{completed} {t('exercises completed on this device','ejercicios completados en este dispositivo')}</p><label className="setting-row"><span>{t('Sound effects','Efectos de sonido')}</span><input type="checkbox" checked={sound} onChange={ev=>{changeSettings({sound:ev.target.checked});cue(ev.target.checked,volume,'step');}}/></label><label className="setting-row"><span>{t('Volume','Volumen')}</span><input type="range" min="0" max="1" step=".05" value={volume} onChange={ev=>changeSettings({volume:Number(ev.target.value)})}/></label><label className="setting-row"><span>{t('Optional five-minute timer','Temporizador opcional de cinco minutos')}</span><input type="checkbox" checked={timed} onChange={ev=>{changeSettings({timed:ev.target.checked});setTimerActive(ev.target.checked);setRemaining(300);}}/></label><div className="settings-info">{t('Belts require correct, unassisted checkpoint answers on different variants, in sessions at least a day apart. Completion alone is not mastery.','Los cinturones requieren respuestas correctas sin ayuda a variantes distintas, en sesiones separadas por al menos un día. Completar no equivale a dominar.')}</div><div className="backup-buttons"><button className="secondary" onClick={exportSave}><Download size={16}/>{t('Export backup','Exportar respaldo')}</button><button className="secondary" onClick={()=>file.current?.click()}><Upload size={16}/>{t('Import backup','Importar respaldo')}</button><input ref={file} type="file" accept="application/json,.json" className="sr-only" onChange={ev=>void importSave(ev.target.files?.[0])}/></div><p className="muted small">{t('Import replaces this device’s progress. Export first to keep a copy.','Importar reemplaza el progreso de este dispositivo. Exporta primero para guardar una copia.')}</p><div className="settings-info">{t('Local execution runs trusted personal code on your computer. It is not a security sandbox. GitHub Pages has no code runner.','La ejecución local corre código personal de confianza en tu equipo. No es un sandbox de seguridad. GitHub Pages no tiene runner.')}</div></section></div>}
 </div>;
}
