import {bi,type Exercise,type Language,type Locale} from './types';
export const beginnerTitles:Record<string,ReturnType<typeof bi>>={variables:bi('Create a variable','Crear una variable'),bindings:bi('Create a variable','Crear una variable'),types:bi('Create a variable','Crear una variable'),values:bi('Create a variable','Crear una variable'),conditions:bi('Make a decision with a condition','Tomar una decisión con una condición'),loops:bi('Repeat instructions with a loop','Repetir instrucciones con un bucle'),functions:bi('Create and call a function','Crear y llamar una función'),methods:bi('Create and call a method','Crear y llamar un método'),collections:bi('Transform the numbers in a list','Transformar los números de una lista')};
export function beginnerLesson(e:Exercise,locale:Locale){
 const t=(en:string,es:string)=>locale==='es'?es:en;const n=e.variant%7+3;const variable=['variables','bindings','types','values'].includes(e.unit);
 const declaration={go:`score := ${n}`,rust:`let mut score = ${n};`,java:`int score = ${n};`,python:`score = ${n}`,scala:`var score = ${n}`}[e.language];
 const syntax={go:t(':= creates a new variable and gives it its first value. Go infers that this value is an integer.','El símbolo := crea una variable nueva y le da su primer valor. Go deduce que este valor es un número entero.'),rust:t('let creates a name for a value. mut lets us assign a new value later. = supplies the starting value.','let crea un nombre para un valor. mut permite asignarle otro valor después. = indica el valor inicial.'),java:t('int means a whole number. score is the name, and = gives it its starting value. ; ends this instruction.','int significa número entero. score es el nombre y = le da el valor inicial. ; termina esta instrucción.'),python:t('= gives a name to a value. Python names refer to objects; this line lets us use score to refer to the number.','= le da un nombre a un valor. En Python los nombres se refieren a objetos; esta línea permite usar score para referirnos al número.'),scala:t('var creates a variable we can change. = gives it its starting value. val would prevent assigning a different value later.','var crea una variable que podemos cambiar. = le da su valor inicial. val impediría asignarle otro valor después.')}[e.language];
 if(variable)return {goal:t('Imagine a game. You have '+n+' points and earn 2 more. How can the program remember your points?','Imagina un juego. Tienes '+n+' puntos y ganas 2 más. ¿Cómo puede el programa recordar tus puntos?'),idea:t('A variable gives a value a name so you can use it again. Here we call it score, which means your points. You choose this name; score is not a special programming word.','Una variable le da un nombre a un valor para poder usarlo después. Aquí elegimos score, que significa puntuación. Tú eliges ese nombre; score no es una palabra especial del lenguaje.'),code:declaration,syntax,meaning:t('Read it as: “Create a variable named score with the value '+n+'.”','Léelo así: «Crea una variable llamada score con el valor '+n+'».')};
 if(e.unit==='conditions')return {goal:t('An order can be ready or still waiting. We want the program to decide by comparing two numbers.','Un pedido puede estar listo o seguir esperando. Queremos que el programa decida comparando dos números.'),idea:t('A condition is a question whose answer is true or false. It chooses which instruction or value to use.','Una condición es una pregunta cuya respuesta es verdadera o falsa. Decide qué instrucción o valor usar.'),code:`${e.language==='go'?'orders':'n'} >= ${n}`,syntax:t('>= asks “is the left number greater than or equal to the right number?” Here both are '+n+', so the answer is true.','>= pregunta «¿el número de la izquierda es mayor o igual al de la derecha?». Aquí ambos son '+n+', así que la respuesta es verdadera.'),meaning:t('ready and wait are words chosen for the output: ready means the order is ready; wait means it needs to wait.','ready y wait son palabras elegidas para la salida: ready significa listo; wait significa esperar.')};
 if(e.unit==='loops')return {goal:t('Add the numbers from 1 to '+n+'. Instead of writing one addition for every number, ask the program to repeat a step.','Suma los números del 1 al '+n+'. En vez de escribir una suma para cada número, pide al programa que repita un paso.'),idea:t('A loop repeats instructions. i is the current number. total (sum in Java) remembers the amount accumulated so far.','Un bucle repite instrucciones. i es el número actual. total (sum en Java) recuerda la cantidad acumulada hasta ahora.'),code:e.language==='java'?'sum += i':'total += i',syntax:t('+= means “add to what we already have”. On each repetition, add the current i to the total.','+= significa «sumar a lo que ya tenemos». En cada repetición, añade el i actual al total.'),meaning:t('Start at zero. Add 1, then 2, then 3, until you have included '+n+'.','Comienza en cero. Suma 1, luego 2, luego 3, hasta incluir '+n+'.')};
 if(e.unit==='collections')return {goal:t('You have two numbers and want to double both. Keep the original list and make a new one.','Tienes dos números y quieres duplicar ambos. Conserva la lista original y crea otra.'),idea:t('A list groups several values. map applies the same transformation to each item and builds a new list.','Una lista agrupa varios valores. map aplica la misma transformación a cada elemento y construye otra lista.'),code:`List(${n}, 2).map(x => x * 2)`,syntax:t('x is the current item. => introduces what to do with it. * means multiply. Each x becomes x times 2.','x es el elemento actual. => introduce qué hacer con él. * significa multiplicar. Cada x se convierte en x por 2.'),meaning:t('The new list is ['+n*2+', 4]. .sum adds those results together.','La nueva lista es ['+n*2+', 4]. .sum suma esos resultados.')};
 const name=e.language==='go'?'double':'twice';return {goal:t('You need to double different numbers. Teach the program this job once, then ask it to do the job whenever you need it.','Necesitas duplicar distintos números. Enseña al programa ese trabajo una vez y pídele que lo haga cuando lo necesites.'),idea:t('A function is a named group of instructions. Calling it means asking it to run. A parameter is a name for the input it receives.','Una función es un grupo de instrucciones con nombre. Llamarla significa pedirle que se ejecute. Un parámetro es un nombre para la entrada que recibe.'),code:`${name}(${n})`,syntax:t(name+' is a name we chose meaning “double”. Parentheses supply the input '+n+'. Inside the function, the parameter x refers to that input.','Elegimos el nombre '+name+' para decir «duplicar». Los paréntesis entregan la entrada '+n+'. Dentro de la función, el parámetro x se refiere a esa entrada.'),meaning:t('x * 2 calculates the double. The function returns (hands back) '+n*2+'; a separate print instruction shows it.','x * 2 calcula el doble. La función devuelve (entrega de vuelta) '+n*2+'; otra instrucción lo muestra en pantalla.')};
}
export function explainBeginnerLine(source:string,language:Language,locale:Locale):string|undefined {
 const t=(en:string,es:string)=>locale==='es'?es:en;const s=source.trim();
 if(!s)return t('This blank line makes the code easier to read. It does not run an instruction.','Esta línea vacía facilita leer el código. No ejecuta ninguna instrucción.');
 if(s==='package main')return t('package groups Go code. main is the special package name for a program you can run. This is different from the main function below.','package agrupa código de Go. main es el nombre especial del paquete de un programa ejecutable. Es distinto de la función main que aparece abajo.');
 if(s.startsWith('import'))return language==='go'?t('import makes a library available. Here fmt supplies the Println function we use to display a value.','import hace disponible una biblioteca. Aquí fmt ofrece la función Println que usamos para mostrar un valor.'):t('import makes library tools available. fmt in Go supplies Println. The Java imports here make utility tools available; this small example does not use them.','import hace disponibles herramientas de bibliotecas. fmt en Go ofrece Println. Los imports de Java de este ejemplo permiten usar utilidades; este ejemplo pequeño no las necesita.');
 if(s.includes('func main()'))return t('func means “define a function”: a named group of instructions. main is the special function Go calls to start this program. () has no inputs here. { opens the group; } closes it.','func significa «define una función»: un grupo de instrucciones con nombre. main es la función especial que Go llama para iniciar este programa. () no recibe entradas aquí. { abre el grupo; } lo cierra.');
 if(s.includes('fn main()'))return t('fn defines a function. main is the function Rust calls when this program starts. The instructions between { and } are its body.','fn define una función. main es la función que Rust llama al iniciar este programa. Las instrucciones entre { y } forman su cuerpo.');
 if(s.includes('public class Main'))return t('class groups Java code. Main is our class name and matches Main.java. Capitalized Main is the class, while lowercase main is the starting method.','class agrupa código de Java. Main es el nombre de nuestra clase y coincide con Main.java. Main con mayúscula es la clase; main con minúscula es el método inicial.');
 if(s.includes('void main'))return t('Java starts in main. public makes it accessible; static allows calling it without creating an object; void means it returns no value. String[] args receives command-line words. throws Exception permits errors to pass to the caller.','Java empieza en main. public lo hace accesible; static permite llamarlo sin crear un objeto; void indica que no devuelve un valor. String[] args recibe palabras de la línea de comandos. throws Exception permite propagar errores al llamador.');
 if(s.includes('@main'))return t('@main tells Scala to make this function a program entrypoint. def defines the function, run is our chosen name, () has no inputs, and Unit means no useful result is returned.','@main indica a Scala que esta función inicia el programa. def define la función, run es el nombre que elegimos, () no recibe entradas y Unit indica que no devuelve un resultado útil.');
 const score=s.match(/score\s*(?::=|=)\s*(\d+)/);
 if(score)return t('Create score with the starting value '+score[1]+'. score is a name chosen by us, meaning points; it is not a keyword. ','Crea score con el valor inicial '+score[1]+'. score es un nombre elegido por nosotros que significa puntos; no es una palabra reservada. ')+({go:t(':= declares and initializes it.',' := lo declara e inicializa.'),rust:t('let declares it; mut permits future changes.','let lo declara; mut permite cambiarlo después.'),java:t('int specifies a whole number.','int especifica un número entero.'),python:t('= binds the name to an integer object.','= vincula el nombre a un objeto entero.'),scala:t('var allows another value to be assigned; val would not.','var permite asignarle otro valor; val no lo permitiría.')}[language]);
 if(s.includes('score +='))return t('Read the old score, add 2, then associate score with the result. += abbreviates score = score + 2. Nothing is printed yet.','Lee score, suma 2 y asocia score con el resultado. += abrevia score = score + 2. Todavía no se muestra nada en pantalla.');

 if(/\b(if|else)\b|\?/.test(s))return t('if asks a true/false question. >= means greater than or equal to. A true answer selects ready; otherwise else selects wait. Java uses ? for the true value and : for the false value. Quotation marks mean literal text.','if plantea una pregunta verdadera o falsa. >= significa mayor o igual. Si es verdadera se elige ready; si no, else elige wait. Java usa ? para el valor verdadero y : para el falso. Las comillas indican texto literal.');
 if(/for |range\(/.test(s))return language==='python'?t('for repeats the indented instructions. i receives each number from range. range(1, n + 1) stops before n + 1, so it includes n.','for repite las instrucciones indentadas. i recibe cada número de range. range(1, n + 1) se detiene antes de n + 1, así que incluye n.'):language==='rust'?t('for repeats its body for each i in the range. 1..=n includes both 1 and n.','for repite su cuerpo para cada i del rango. 1..=n incluye tanto 1 como n.'):t('Repeat for each number. i holds the current number. Go and Java use <= to include the endpoint and i++ to advance by one. Rust 1..=n includes n. Python range(1, n + 1) stops before n + 1, so n is included.','Repite para cada número. i contiene el número actual. Go y Java usan <= para incluir el límite e i++ para avanzar uno. En Rust, 1..=n incluye n. En Python, range(1, n + 1) se detiene antes de n + 1, por lo que incluye n.');
 if(/(total|sum)\s*\+=/.test(s))return t('Add the current i to the accumulated total. Keep the result for the next repetition.','Suma el i actual al total acumulado. Conserva el resultado para la siguiente repetición.');
 if(/(total|sum)\s*(?::=|=)\s*0/.test(s))return t('Start the running total at zero, because we have not added any numbers yet.','Inicia el total acumulado en cero porque todavía no hemos sumado ningún número.');
 if(/\.map\(/.test(s))return t('map makes a new list: for each x, x * 2 produces double its value. .sum adds that new list. println displays the final sum.','map crea otra lista: para cada x, x * 2 produce el doble de su valor. .sum suma esa nueva lista. println muestra la suma final.');
 if(/List\(/.test(s))return t('List groups these numbers. values is our chosen name for the list. val prevents reassigning that name.','List agrupa estos números. values es el nombre que elegimos para la lista. val impide reasignar ese nombre.');
 if(/(?:orders|n)\s*(?::=|=)\s*\d/.test(s))return t('Give the input number a name so the comparison can refer to it. orders means the number of orders; n is a short name for a number.','Dale un nombre al número de entrada para usarlo en la comparación. orders significa cantidad de pedidos; n es un nombre corto para un número.');
 if(/^(func |fn |def |static int )/.test(s))return t('Define a reusable function. double or twice is our chosen name. x is its input parameter. int, i32, or Int (where present) specify whole-number inputs or results. Defining a function does not yet call it.','Define una función reutilizable. double o twice es el nombre que elegimos. x es su parámetro de entrada. int, i32 o Int (cuando aparecen) indican entradas o resultados enteros. Definir una función todavía no la ejecuta.');
 if(/return|x \* 2/.test(s)&&!/print|Println/.test(s))return t('Multiply the input x by 2 and return the result to the caller. Rust and Scala can return their final expression without the word return.','Multiplica la entrada x por 2 y devuelve el resultado a quien llamó. Rust y Scala pueden devolver la expresión final sin escribir return.');
 if(/println|Println|print\(/.test(s))return t('Show a value on the screen. The expression inside the parentheses is evaluated first. score means use its value, not the letters “score”. In Rust, {} is a placeholder replaced by the value after the comma.','Muestra un valor en pantalla. Primero se evalúa la expresión dentro de los paréntesis. score significa usar su valor, no las letras «score». En Rust, {} es un espacio que se reemplaza por el valor después de la coma.');
 if(/^[{}]+$/.test(s))return t('This brace marks a group boundary. } ends the group of instructions. It does not erase the text already printed.','Esta llave marca el límite de un grupo. } termina el grupo de instrucciones. No borra el texto ya mostrado.');
 return undefined;
}
