import type {Exercise,Locale} from './types';
export default function ConceptAnimation({lesson,locale,frame,playing,speed}:{lesson:Exercise;locale:Locale;frame:number;playing:boolean;speed:number}){
 const t=(en:string,es:string)=>locale==='es'?es:en,n=lesson.variant%7+3;const variable=['variables','bindings','types','values'].includes(lesson.unit);const loop=lesson.unit==='loops',condition=lesson.unit==='conditions',list=lesson.unit==='collections';
 const label=t('Points remembered by the program','Puntos que recuerda el programa');const dots=Array.from({length:variable?(frame>=2?n+2:n):loop?(frame*(frame+1)/2):n},(_,i)=>i);
 return <div className={`concept-animation ${playing?'is-playing':'is-stepping'}`} style={{'--travel-time':`${1.2/speed}s`} as React.CSSProperties}>
 <svg viewBox="0 0 520 250" role="img" aria-label={variable?t(`score remembers ${frame>=2?n+2:n} points. ${frame===1?'Two bonus points are being added.':frame===3?'The value is copied to the screen.':''}`,`score recuerda ${frame>=2?n+2:n} puntos. ${frame===1?'Se están sumando dos puntos extra.':frame===3?'Se copia el valor a la pantalla.':''}`):t('Follow the highlighted calculation and its result.','Sigue el cálculo resaltado y su resultado.')}>
 {variable?<>
 <text x="28" y="25" className="scene-label">{label}</text><rect x="25" y="48" width="220" height="150" rx="18" className="scene-box"/><text x="44" y="77" className="scene-label">score · {t('our chosen name','nombre elegido')}</text>
 <g key={`points-${frame}`} className="points-enter">{dots.map(i=><circle key={i} cx={48+(i%6)*30} cy={104+Math.floor(i/6)*29} r="9" className={i>=n?'bonus-dot':'point-dot'}/>)}</g><text x="225" y="179" textAnchor="end" className="scene-number">{frame>=2?n+2:n}</text>
 {frame===1&&<g key="bonus" className="bonus-transfer"><rect x="326" y="60" width="128" height="55" rx="13" className="scene-box bonus-box"/><text x="390" y="95" textAnchor="middle" className="scene-number">+2</text></g>}
 {frame===2&&<><text x="310" y="95" className="scene-label">{t('Old → new','Antes → ahora')}</text><text x="310" y="135" className="scene-number">{n} → {n+2}</text></>}
 <rect x="300" y="160" width="195" height="65" rx="10" className="screen-box"/><text x="315" y="180" className="scene-label">{t('Screen output','Salida en pantalla')}</text>{frame===3?<g key="output" className="output-transfer"><text x="394" y="212" textAnchor="middle" className="scene-number">{n+2}</text></g>:<text x="393" y="209" textAnchor="middle" className="scene-label">{t('nothing yet','todavía nada')}</text>}
 </>:condition?<>
 <rect x="25" y="90" width="100" height="70" rx="14" className="scene-box"/><text x="75" y="132" textAnchor="middle" className="scene-number">{n}</text><path d="M130 125H205M305 125L370 65M305 125L370 195" className="scene-path"/><polygon points="255,65 320,125 255,185 190,125" className="scene-box"/><text x="255" y="130" textAnchor="middle" className="scene-label">≥ {n}?</text><rect x="370" y="35" width="125" height="65" rx="12" className={frame>=2?'branch-selected':'scene-box'}/><text x="433" y="63" textAnchor="middle" className="scene-label">{t('yes / ready','sí / listo')}</text><text x="433" y="85" textAnchor="middle" className="scene-label">ready</text><rect x="370" y="162" width="125" height="65" rx="12" className="branch-muted"/><text x="433" y="199" textAnchor="middle" className="scene-label">wait</text>{frame>=2&&<circle key={frame} r="9" cx="384" cy="67" className="decision-traveler"/>}
 </>:loop?<>
 <text x="25" y="28" className="scene-label">{t('Add one number each time','Suma un número cada vez')}</text>{Array.from({length:n},(_,i)=><g key={i}><rect x={25+i*49} y="48" width="40" height="40" rx="10" className={frame===i+1?'branch-selected':'scene-box'}/><text x={45+i*49} y="74" textAnchor="middle" className="scene-label">{i+1}</text></g>)}<path d="M70 108Q260 240 440 108" className="scene-path"/><rect x="160" y="143" width="200" height="77" rx="16" className="scene-box"/><text x="182" y="166" className="scene-label">{lesson.language==='java'?'sum':'total'}</text><text key={frame} x="260" y="201" textAnchor="middle" className="scene-number points-enter">{frame===0?0:Math.min(frame,n)*(Math.min(frame,n)+1)/2}</text>{frame>0&&frame<=n&&<text key={`add-${frame}`} x="260" y="123" textAnchor="middle" className="scene-number add-traveler">+{frame}</text>}
 </>:<>
 <text x="25" y="30" className="scene-label">{list?t('Each item makes the same trip','Cada elemento hace el mismo recorrido'):t('A function receives, calculates, and returns','Una función recibe, calcula y devuelve')}</text><rect x="22" y="90" width="115" height="80" rx="15" className="scene-box"/><text x="79" y="119" textAnchor="middle" className="scene-label">{t('Input','Entrada')}</text><text x="79" y="151" textAnchor="middle" className="scene-number">{list?`${n}, 2`:n}</text><path d="M139 130H199M321 130H380" className="scene-path"/><rect x="200" y="75" width="120" height="110" rx="20" className={frame===1?'branch-selected':'scene-box'}/><text x="260" y="110" textAnchor="middle" className="scene-label">{list?'map':lesson.language==='go'?'double':'twice'}</text><text x="260" y="153" textAnchor="middle" className="scene-number">× 2</text><rect x="381" y="90" width="116" height="80" rx="15" className="scene-box"/><text x="439" y="119" textAnchor="middle" className="scene-label">{t('Result','Resultado')}</text><text x="439" y="151" textAnchor="middle" className="scene-number">{frame>=2?(list?`${n*2}, 4`:n*2):'?'}</text>{frame===1&&<circle r="8" cx="204" cy="130" className="function-input"/>}{frame>=2&&<circle key={frame} r="8" cx="381" cy="130" className="function-output"/>}{list&&frame===3&&<text x="260" y="230" textAnchor="middle" className="scene-label">{n*2} + 4 = {lesson.expected}</text>}
 </>}
 </svg><p className="model-note">{t('A teaching picture of the values, not a physical memory layout.','Un dibujo para entender los valores, no la ubicación física en memoria.')}</p>
 </div>;
}
