import LineExplorer from './LineExplorer';
import {useEffect,useState} from 'react';import {Play,Pause,SkipBack,ChevronLeft,ChevronRight,Check,ArrowRight} from 'lucide-react';
import {labs,type Choice} from './content/labs';import type {Locale} from './types';
import {stateLabel} from './state-labels';
export {labs};
export function Choices({choices,locale,onResult,locked=false}:{choices:Choice[];locale:Locale;onResult:(correct:boolean)=>void;locked?:boolean}){
 const [selected,setSelected]=useState<number|null>(null);
 return <div className="choices">{choices.map((c,i)=><button key={i} disabled={selected!==null||locked} className={`choice ${selected===i?(c.correct?'correct':'incorrect'):''}`} onClick={()=>{setSelected(i);onResult(c.correct);}}><span className="choice-letter">{String.fromCharCode(65+i)}</span><span>{c.text[locale]}</span>{selected===i&&c.correct&&<Check size={17}/>}</button>)}{selected!==null&&<p className="rationale" role="status">{choices[selected].why[locale]}</p>}</div>;
}
export default function LabView({id,locale,onAttempt,onStep}:{id:string;locale:Locale;onAttempt:(correct:boolean,variant:number,checkpoint:boolean)=>void;onStep:()=>void}){
 const [view,setView]=useState<'simple'|'technical'>('simple');
 const lab=labs.find(l=>l.id===id)??labs[0];const [scenarioIndex,setScenario]=useState(0),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[predicted,setPredicted]=useState(false),[followup,setFollowup]=useState(false);
 const s=lab.scenarios[scenarioIndex],frame=s.frames[step],last=step===s.frames.length-1;
 useEffect(()=>{setScenario(0);setStep(0);setPlaying(false);setPredicted(false);setFollowup(false);},[id]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStep(v=>{if(v>=s.frames.length-2&&!predicted){setPlaying(false);return s.frames.length-2;}if(v>=s.frames.length-1){setPlaying(false);return v;}return v+1;}),1600/speed);return()=>clearInterval(timer);},[playing,speed,s,predicted]);
 const change=(v:number)=>{setPlaying(false);setStep(Math.max(0,Math.min(s.frames.length-1,v)));onStep();};
 const positions=s.nodes.map((_,i)=>lab.layout==='lanes'?{x:25+(i%2)*245,y:25+Math.floor(i/2)*128}:lab.layout==='stack'?{x:30+(i%2)*230,y:25+Math.floor(i/2)*128}:{x:25+(i%2)*245,y:25+Math.floor(i/2)*128});
 const gate=step===s.frames.length-2&&!predicted;
 return <div className="lab-content">
  <div className="section-kicker">{locale==='es'?'LABORATORIO VISUAL':'VISUAL LAB'} <span>• {locale==='es'?'MODELO CONCEPTUAL':'CONCEPTUAL MODEL'}</span></div>
  <h2>{lab.title[locale]}</h2><p className="lede">{lab.subtitle[locale]}</p>
  <div className="scenario-switch">{lab.scenarios.map((x,i)=><button key={i} aria-pressed={scenarioIndex===i} className={scenarioIndex===i?'selected':''} onClick={()=>{setScenario(i);setStep(0);setPlaying(false);setPredicted(false);setFollowup(false);}}>{i+1}. {x.title[locale]}</button>)}</div>
  <div className="view-tabs" role="tablist" aria-label={locale==='es'?'Detalle de explicación':'Explanation detail'}>{(['simple','technical'] as const).map(v=><button role="tab" key={v} aria-selected={view===v} onClick={()=>setView(v)}>{v==='simple'?'Simple':locale==='es'?'Técnica · estado y código':'Technical · state & code'}</button>)}</div>
  {view==='simple'?<div className="diagram"><svg viewBox={`0 0 490 ${s.nodes.length>2?270:150}`} role="img" aria-label={frame.description[locale]}><defs><marker id={`arrow-${id}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#a9cc6c"/></marker></defs>{frame.edges.map(([a,b],i)=>{const p=positions[a],q=positions[b];const down=q.y>p.y,up=q.y<p.y;const x1=p.x+100,y1=down?p.y+75:up?p.y:p.y+37,x2=q.x+100,y2=down?q.y:up?q.y+75:q.y+37;return <path key={`${a}-${b}`} className="flow-edge" d={p.y===q.y?`M${q.x>p.x?p.x+200:p.x} ${y1} L${q.x>p.x?q.x:q.x+200} ${y2}`:`M${x1} ${y1} C${x1} ${(y1+y2)/2},${x2} ${(y1+y2)/2},${x2} ${y2}`} markerEnd={`url(#arrow-${id})`} style={{animationDelay:`${i*.2}s`}}/>;})}{s.nodes.map((node,i)=><g key={i} className={`diagram-node ${frame.active.includes(i)?'active':''}`} transform={`translate(${positions[i].x},${positions[i].y})`}><rect width="200" height="75" rx="10"/><text x="15" y="26" className="node-label">{node[locale]}</text><text x="15" y="53" className="node-value">{stateLabel(frame.values[i],locale)}</text><circle cx="180" cy="22" r="4"/></g>)}</svg></div>:<div className="technical-state"><h3>{locale==='es'?'Estado del modelo':'Model state'} · {step+1}</h3><dl>{s.nodes.map((node,i)=><div key={i}><dt>{node[locale]}</dt><dd>{stateLabel(frame.values[i],locale)}</dd></div>)}</dl></div>}
  <div className="playback"><button aria-label={locale==='es'?'Reiniciar':'Replay'} onClick={()=>change(0)}><SkipBack size={17}/></button><button aria-label={locale==='es'?'Paso anterior':'Previous step'} disabled={step===0} onClick={()=>change(step-1)}><ChevronLeft size={18}/></button><button className="play-button" aria-label={playing?(locale==='es'?'Pausar':'Pause'):(locale==='es'?'Reproducir':'Play')} disabled={gate||last} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label={locale==='es'?'Paso siguiente':'Next step'} disabled={gate||last} onClick={()=>change(step+1)}><ChevronRight size={18}/></button><span>{step+1} / {s.frames.length}</span><select aria-label={locale==='es'?'Velocidad':'Playback speed'} value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div>
  <p className="frame-description" aria-live="polite">{frame.description[locale]}</p>
  {view==='technical'&&<LineExplorer key={id+'-'+scenarioIndex} code={s.code} locale={locale} active={frame.line-1} explanation={frame.description[locale]}/>}<p className="model-note">{lab.model[locale]}</p>
  {gate&&<div className="checkpoint"><div className="section-kicker">{locale==='es'?'PREDICE ANTES DE CONTINUAR':'PREDICT BEFORE CONTINUING'}</div><h3>{s.question[locale]}</h3><Choices key={`${id}-${scenarioIndex}-predict`} choices={s.choices} locale={locale} onResult={correct=>{setPredicted(true);onAttempt(correct,scenarioIndex,true);}}/></div>}
  {predicted&&!last&&<button className="secondary" onClick={()=>change(step+1)}>{locale==='es'?'Ver el resultado':'Reveal the outcome'}<ArrowRight size={16}/></button>}
  {last&&<div className="checkpoint"><div className="section-kicker">{locale==='es'?'APLICA LA IDEA':'APPLY THE IDEA'}</div><h3>{lab.followup.prompt[locale]}</h3><Choices key={`${id}-${scenarioIndex}-followup`} choices={lab.followup.choices} locale={locale} locked={followup} onResult={correct=>{setFollowup(true);onAttempt(correct,scenarioIndex,false);}}/></div>}
 </div>;
}
